### PR TITLE
On boarding pages

### PR DESCRIPTION
**Pull request by FaizFk**
This is my solution for Issue #3 

1) I have used PageView Widget which is prebuilt in flutter to make horizontal scrolling effect.
2) I have used smooth_page_indicator package to make the three dots which also helps to navigate.
3) buildPage function returns the main content of onboarding pages, currently it has title and description as specified in figma design. You can alter this function to add more content in onboarding main content.
4) If you ever want to add a new onboarding page then just add that buildPage entry in onboardingPageList variable.

If you have any issues feel free to contact me, I will try my best to correct them.

### CODE REVIEW

**Comment by Him-anshuSharma** [comment]
@FaizFk  Can you attach screenshots or a screen recording of the splashscreen

**Comment by FaizFk** [comment]
Sure, give me 5 minutes

**Comment by Him-anshuSharma** [comment]
> Sure, give me 5 minutes

sure

**Comment by FaizFk** [comment]
@Him-anshuSharma 

https://user-images.githubusercontent.com/72645960/194719055-791e8b28-5469-4f29-82f5-d08794c9b176.mp4

**Comment by Him-anshuSharma** [comment]
Awesome work, I'll review it and then merge!

**Comment by FaizFk** [comment]
@Him-anshuSharma 
If there is any problem, feel free to ask me.

**Comment by Him-anshuSharma** [comment]
> @Him-anshuSharma 
> If there is any problem, feel free to ask me.

Sure

**Comment by Him-anshuSharma** [comment]
@FaizFk  Hey  great work, everything is fine. Just two minor changes. 

1. After going home screen, I don't want to navigate back to previous screen on pressing back. Just replace _Navigator.pushNamed(context, '/route')_ to _Navigator.pushReplacementNamed(context, '/route')_
2. There is pixel overflow on rotating the screen. Instead of 'SizedBox(_)' ,try using 
`Expanded(child:SizedBox(_))`

**Comment by FaizFk** [comment]
> @FaizFk  Hey  great work, everything is fine. Just two minor changes. 
> 
> 1. After going home screen, I don't want to navigate back to previous screen on pressing back. Just replace _Navigator.pushNamed(context, '/route')_ to _Navigator.pushReplacementNamed(context, '/route')_
> 2. There is pixel overflow on rotating the screen. Instead of `SizedBox(_)`,try using 
> `Expanded(child:SizedBox())`

Sure I will do these things, first in the morning.

**Comment by Him-anshuSharma** [comment]
> Sure I will do these things, first in the morning.

No worries!

**Comment by FaizFk** [comment]
@Him-anshuSharma  I have used pushReplacementNamed instead of pushNamed, but I was not able to get my head around to use the expanded widget as the UI was getting drastically changed(not looked consistent), So I instead created a bool variable isLandscape and according to it I decreased vertical padding. I have checked the changes in many devices and its working pretty well.

Can you recheck...

**Comment by Him-anshuSharma** [comment]
Sure, I'll check it.

**Comment by FaizFk** [comment]
@Him-anshuSharma 
is there any issue??

**Comment by FaizFk** [comment]
Looks like you my code got merged, but Pull Request is still open. Is there any issue??
Sorry I am new to github.

**Comment by Him-anshuSharma** [comment]
> Looks like you my code got merged, but Pull Request is still open. Is there any issue?? Sorry I am new to GitHub.

Hey @FaizFk PR is closed, try refreshing. Btw Good job!

**Comment by FaizFk** [comment]
Yes it has, also thank you for guidance😄

**Pull request merged**
